options:
  dbpath:
    default: "/var/lib/mongodb"
    type: string
    description: The path where the data files will be kept.
  logpath:
    default: "/var/log/mongodb/mongodb.log"
    type: string
    description: The path where to send log data.
  logappend:
    default: True
    type: boolean
    description: Append log entries to existing log file
  logrotate-frequency:
    default: daily
    type: string
    description: How often should the logs be rotated. Use values from logrotate.
  logrotate-rotate:
    default: 5
    type: int
    description: Number of log files to keep.
  logrotate-maxsize:
    default: 500M
    type: string
    description: Maximum log size before rotating.
  bind_ip:
    default: "all"
    type: string
    description: IP address that mongodb should listen for connections.
  port:
    default: 27017
    type: int
    description: Default MongoDB port
  journal:
    default: True
    type: boolean
    description: Enable journaling, http://www.mongodb.org/display/DOCS/Journaling
  cpu:
    default: False
    type: boolean
    description: Enables periodic logging of CPU utilization and I/O wait
  auth:
    default: False
    type: boolean
    description: Turn on/off security
  verbose:
    default: False
    type: boolean
    description: Verbose logging output
  objcheck:
    default: False
    type: boolean
    description: Inspect all client data for validity on receipt (useful for developing drivers)
  quota:
    default: False
    type: boolean
    description: Enable db quota management
  diaglog:
    default: 0
    type: int
    description: Set oplogging level where n is 0=off (default), 1=W, 2=R, 3=both, 7=W+some reads
  nocursors:
    default: False
    type: boolean
    description: Diagnostic/debugging option
  nohints:
    default: False
    type: boolean
    description: Ignore query hints
  noscripting:
    default: False
    type: boolean
    description: Turns off server-side scripting.  This will result in greatly limited functionality
  notablescan:
    default: False
    type: boolean
    description: Turns off table scans.  Any query that would do a table scan fails
  noprealloc:
    default: False
    type: boolean
    description: Disable data file preallocation
  nssize:
    default: "default"
    type: string
    description: Specify .ns file size for new databases
  mms-token:
    default: "disabled"
    type: string
    description: Accout token for Mongo monitoring server
  mms-name:
    default: "disabled"
    type: string
    description: Server name for Mongo monitoring server
  mms-interval:
    default: "disabled"
    type: string
    description: Ping interval for Mongo monitoring server ( in number of seconds )
  autoresync:
    default: False
    type: boolean
    description: Automatically resync if slave data is stale
  oplogSize:
    default: "default"
    type: string
    description: Custom size for replication operation log
  opIdMem:
    default: "default"
    type: string
    description: Size limit for in-memory storage of op ids
  replicaset:
    default: myset
    type: string
    description: Name of the replica set
  web_admin_ui:
    default: True
    type: boolean
    description: Replica Set Admin UI (accessible via default_port + 1000)
  replicaset_master:
    default: auto
    type: string
    description: Replica Set master (optional). Possible values are 'auto' for automatic detection based on install time or 'host:port' to connect to 'host' on 'port' and register as a member.
  master:
    default: "self"
    type: string
    description: Who is the master DB. If not "self", put the Master DB here as "host:port"
  config_server_port:
    default: 27019
    type: int
    description: Port number to use for the config-server
  config_server_dbpath:
    default: "/mnt/var/lib/mongodb/configsvr"
    type: string
    description: The path where the config server data files will be kept.
  config_server_logpath:
    default: "/mnt/var/log/mongodb/configsvr.log"
    type: string
    description: The path where to send config server log data.
  arbiter:
    default: "disabled"
    type: string
    description: Enable arbiter mode. Possible values are 'disabled' for no arbiter, 'enable' to become an arbiter or 'host:port' to declare another host as an arbiter.  replicaset_master must be set for this option to work.
  mongos_logpath:
    default: "/mnt/var/log/mongodb/mongos.log"
    type: string
    description: The path where to send log data from the mongo router.
  mongos_port:
    default: 27021
    type: int
    description: Port number to use for the mongo router
  extra_config_options:
    default: "none"
    type: string
    description: Extra options ( comma separated ) to be included ( at the end ) in the mongodb.conf file.
  extra_daemon_options:
    default: "none"
    type: string
    description: Extra options ( exactly as you would type them in the command line ) to be added via the command line to the mongodb daemon
  backups_enabled:
    default: False
    type: boolean
    description: Enable daily backups to disk.
  backup_directory:
    default: "/home/ubuntu/backups"
    type: string
    description: Where can the backups be found.
  backup_copies_kept:
    default: 7
    type: int
    description: "Number of backups to keep. Keeps one week's worth by default."
  #------------------------------------------------------------------------
  # Volume management
  #   volume-map, volume-dev_regexp are only used 
  #   if volume-ephemeral-storage == False
  #------------------------------------------------------------------------
  volume-ephemeral-storage:
    type: boolean
    default: true
    description: >
      If false, a configure-error state will be raised if
         volume-map[$JUJU_UNIT_NAME] is not set (see "volume-map"
         below) - see "volume-map" below.
      If true, service units won't try to use "volume-map" (and
         related variables) to mount and use external (EBS) volumes,
         thus storage lifetime will equal VM, thus ephemeral.
         YOU'VE BEEN WARNED.
  volume-map:
    type: string
    default: ""
    description: >
      YAML map as e.g. "{ mongodb/0: vol-0000010, mongodb/1: vol-0000016 }".
      Service units will raise a "configure-error" condition if no volume-map
      value is set for it - it expects a human to set it properly to resolve it.
  volume-dev-regexp:
    type: string
    default: "/dev/vd[b-z]"
    description: >
      Block device for attached volumes as seen by the VM, will be "scanned"
      for an unused device when "volume-map" is valid for the unit.
  source:
    type: string
    default: None
    description: >
      Optional configuration to support use of additional sources such as:
        - ppa:myteam/ppa
        - cloud:precise-proposed/icehouse
        - http://my.archive.com/ubuntu main
      The last option should be used in conjunction with the key configuration
      option.
  key:
    type: string
    description: >
      Key ID to import to the apt keyring to support use with arbitary source
      configuration from outside of Launchpad archives or PPA's.
