#!/bin/bash

############################################################################################################
# Set debugging information
############################################################################################################

set -ux


############################################################################################################
# Set global variables
############################################################################################################

MY_HOSTNAME=`relation-get hostname`
MY_PORT=`relation-get port`


############################################################################################################
# Modify the redis configuration to become a slave and restart redis so changes take effect.
############################################################################################################

sed -i.bak -e "s/\# slaveof.*/slaveof ${MY_HOSTNAME} ${MY_PORT}/" /etc/redis/redis.conf

service redis-server status && service redis-server restart || service redis-server start

