#!/bin/bash

############################################################################################################
# Set debugging information
############################################################################################################

set -ux


############################################################################################################
# Modify the redis configuration to break the master/slave relationship and be stand-alone.
# Restart redis-server so changed take effect.
############################################################################################################

sed -i.bak -e "s/slaveof /\#slaveof /" /etc/redis/redis.conf

service redis-server status && service redis-server restart || service redis-server start

