#!/bin/bash

set -ue

apt-get -y install pwgen

PASSWD_FILE="/var/lib/juju/nagios.passwd"
if [[ -e $PASSWD_FILE ]] ; then
	PASSWORD=$(cat $PASSWD_FILE)
else
	PASSWORD=$(pwgen 10 1)
	echo $PASSWORD >$PASSWD_FILE
	chmod 0400 $PASSWD_FILE
fi

echo nagios3-cgi nagios3/adminpassword password $PASSWORD | debconf-set-selections
echo nagios3-cgi nagios3/adminpassword-repeat password $PASSWORD | debconf-set-selections

DEBIAN_FRONTEND=noninteractive apt-get -qy \
	install nagios3 nagios-plugins python-cheetah python-jinja2 dnsutils debconf-utils nagios-nrpe-plugin

# Ideally these would be moved into the distro ASAP
if [ -d debs ] ; then
    dpkg -i debs/*.deb
fi

# enable external commands per README.Debian file
if ! grep '^check_external_commands=1$' /etc/nagios3/nagios.cfg ; then
    echo check_external_commands=1 >> /etc/nagios3/nagios.cfg
fi
# || :'s are for idempotency
service nagios3 stop || :
dpkg-statoverride --update --add nagios www-data 2710 /var/lib/nagios3/rw || :
dpkg-statoverride --update --add nagios nagios 751 /var/lib/nagios3 || :
service nagios3 start

# For the admin interface
open-port 80
