#!/bin/bash
sslcfg=`config-get ssl`

if [ "$sslcfg" == "only" ]; then
    relation-set hostname=`unit-get private-address` port=443
else
    relation-set hostname=`unit-get private-address` port=80
fi
