#!/bin/bash

############################################################################################################
# Debugging information
############################################################################################################
set -ux


############################################################################################################
# Set the language
############################################################################################################
LANG=en_US.UTF-8


############################################################################################################
# Dependency and utility packages
############################################################################################################
apt-add-repository ppa:facter-plugins/ppa
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get -y install debconf-utils python-software-properties pwgen facter facter-customfacts-plugin curl


############################################################################################################
# Global variables
############################################################################################################
# MySQL
MYSQL_ROOT_PASSWORD=`pwgen -N1`
MYSQL_TOKEN=`pwgen -N1`

# DynDNS
USE_DYNDNS="false"
DYNDNS_USERNAME="xxxxx"
DYNDNS_PASSWORD="xxxxx"
DYNDNS_HOSTNAME="xxxxx"

# CloudFoundry Server
CF_SERVER_IP=`facter ipaddress`

# Install time
INSTALL_TIME=`date +%s`


############################################################################################################
# Add repositories
############################################################################################################
apt-add-repository ppa:cloudfoundry/ppa
apt-get -y update


############################################################################################################
# Preseed variables
############################################################################################################

# Mysql
echo debconf mysql-server/root_password password ${MYSQL_ROOT_PASSWORD}| /usr/bin/debconf-set-selections
echo debconf mysql-server/root_password_again password ${MYSQL_ROOT_PASSWORD}| /usr/bin/debconf-set-selections

# Postfix
echo debconf postfix/main_mailer_type select No configuration | /usr/bin/debconf-set-selections

# CloudFoundry
echo debconf cloudfoundry-server/use_dyndns boolean ${USE_DYNDNS} | /usr/bin/debconf-set-selections
echo debconf cloudfoundry-server/hostname string api.${DYNDNS_HOSTNAME} | /usr/bin/debconf-set-selections
echo debconf cloudfoundry-server-dea/ip string ${CF_SERVER_IP} | /usr/bin/debconf-set-selections
echo debconf cloudfoundry-server/ip string ${CF_SERVER_IP} | /usr/bin/debconf-set-selections

fact-add install-time ${INSTALL_TIME}


############################################################################################################
# Install CloudFoundry package
############################################################################################################
DEBIAN_FRONTEND=noninteractive apt-get -y install cloudfoundry-server


############################################################################################################
# Configure redis for cloudfoundry-server
############################################################################################################
sed -i -e "s/^node_id:.*/node_id: redis_node_${INSTALL_TIME}/" \
       -e "s/^index:.*/index: ${INSTALL_TIME}/" \
       /opt/cloudfoundry-server/vcap/services/redis/config/redis_node.yml


############################################################################################################
# Stop CloudFoundry ( due to LP:810808 )
############################################################################################################
service cloudfoundry-server stop
cd /opt/cloudfoundry-server/vcap && HOME=/root rake db:migrate && cd -


############################################################################################################
# Open the necessary firewall/ACL ports
############################################################################################################
if [ -x /usr/bin/open-port ]; then
   open-port 80/TCP
   open-port 443/TCP
fi

exit 0
